# Generated by Django 4.1.1 on 2022-12-30 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.SmallIntegerField()),
                ('avgPace', models.DecimalField(decimal_places=2, max_digits=4)),
                ('detail', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Xtrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.SmallIntegerField()),
                ('detail', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RunWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_1', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('day_2', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('day_3', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('day_4', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('restday_1', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('restday_2', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('restday_3', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('total', models.SmallIntegerField()),
                ('run_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_1', to='training.run')),
                ('run_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_2', to='training.run')),
                ('run_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_3', to='training.run')),
                ('run_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_4', to='training.run')),
                ('xtrain_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xtrain_1', to='training.xtrain')),
                ('xtrain_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xtrain_2', to='training.xtrain')),
                ('xtrain_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xtrain_3', to='training.xtrain')),
            ],
        ),
    ]
