# Generated by Django 4.1.1 on 2022-12-30 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalfMarathonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfWeeks', models.SmallIntegerField()),
                ('shortName', models.CharField(max_length=128)),
                ('runWeek_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runweek_1', to='training.runweek')),
                ('runWeek_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runweek_10', to='training.runweek')),
                ('runWeek_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runweek_11', to='training.runweek')),
                ('runWeek_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runweek_12', to='training.runweek')),
                ('runWeek_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runweek_2', to='training.runweek')),
                ('runWeek_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runweek_3', to='training.runweek')),
                ('runWeek_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runweek_4', to='training.runweek')),
                ('runWeek_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runweek_5', to='training.runweek')),
                ('runWeek_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runweek_6', to='training.runweek')),
                ('runWeek_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runweek_7', to='training.runweek')),
                ('runWeek_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runweek_8', to='training.runweek')),
                ('runWeek_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runweek_9', to='training.runweek')),
            ],
        ),
    ]
