# Generated by Django 4.1.1 on 2022-12-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_halfmarathonplan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HalfMarathonPlan',
            new_name='HalfMarathon',
        ),
    ]
