# Generated by Django 4.1.1 on 2022-12-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_rename_halfmarathonplan_halfmarathon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='halfmarathon',
            old_name='shortName',
            new_name='name',
        ),
        migrations.AddField(
            model_name='run',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
