# Generated by Django 4.1.1 on 2023-01-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_run_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='xtrain',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
