# Generated by Django 4.1.1 on 2023-01-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_xtrain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='runweek',
            name='week',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
