# Generated by Django 4.1.1 on 2023-01-02 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_xtrain_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfWeeks', models.SmallIntegerField()),
                ('name', models.CharField(max_length=128)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=4)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RunSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.race')),
                ('runWeek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runweek', to='training.runweek')),
            ],
        ),
        migrations.DeleteModel(
            name='HalfMarathon',
        ),
    ]
