# Generated by Django 4.1.1 on 2023-01-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_race_runschedule_delete_halfmarathon'),
    ]

    operations = [
        migrations.AddField(
            model_name='runweek',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
