# Generated by Django 4.1.1 on 2023-01-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_runweek_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runweek',
            name='total',
            field=models.SmallIntegerField(default=0),
        ),
    ]
